version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kraken
      POSTGRES_USER: kraken
    ports:
          - 5432:5432

#  db_migrate:
#    command:

