version: '3.1'

services:

  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - profile/migration/_env
    ports:
          - 5432:5432 # todo port does not need to be external

  db-migrate:
    container_name: db-migrate
    build: ./profile/migration/
    env_file:
          - profile/migration/_env
    depends_on:
      - db
    links:
      - db

  db-data:
    container_name: db-data
    build:
      context: .
      dockerfile: ./profile/data/Dockerfile
    depends_on:
      - db-migrate
    links:
      - db
    env_file:
      - profile/data/_env

#  transaction-processor:
#    container_name: transaction-processor
#    build: .