version: '3.1'

services:

  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - ./kraken_env
#    volumes:
#          - ./profile/migration/init.sql:/docker-entrypoint-initdb.d/
    ports:
          - 5432:5432 # port does not need to be external but makes looking at data easier

  transaction-processor:
    container_name: transaction-processor
    build: .
    depends_on:
        - db
    env_file:
        - _env
    links:
        - db