version: '3.1'

services:

  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - ./kraken_env

  transaction-processor:
    container_name: transaction-processor
    build: .
    depends_on:
        - db
    env_file:
        - _env
    links:
        - db