version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kraken
      POSTGRES_USER: kraken
    ports:
          - 5432:5432

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

#  db-migration:
#    command:

